### ISSUE TITLE
Local testing

### ISSUE THREAD

**Issue by japo32** [verbb/social-feeds#6]
### Question

Is local testing possible? Based on what I can see a site that uses the plugin needs to be public facing in order to get the proper token from Meta.

What config would you recommend for multi environment setups? (local, test, prod)

Cheers

**Comment by engram-design** [comment]
I believe local testing works for Facebook and Instagram! You can use a local domain like `mysite.test` just fine.

As for my recommendation, it's up to you. I used to use a separate app for each environment, but that got tiresome. You can have multiple domains and callbacks for Facebook/Instagram, so it shouldn't be a problem.

**Comment by japo32** [comment]
Hi Josh,
I am using `http://localhost:8080/` and have added localhost to the list of domains on FB, but I get an error that says `OAuth Redirect URIs` can't be accessed.

**Comment by engram-design** [comment]
From what I've read, that's fine - the only requirement is that it needs to be HTTPS, even for local. So it might be an option to set up a virtual host with Valet, DDEV, Docket, MAMP, or whatever you use for development.

Otherwise, we may need to add a setting to use our proxy which forwards requests through our server to yours. Some providers use this like YouTube.

**Comment by japo32** [comment]
ah that might be it, I'm only on http for local. thanks!
